<!DOCTYPE html>
<html lang="en">

<?php require_once 'head.phtml' ?>

<body data-spy="scroll" data-target=".main-nav" data-offset="82">

<!---//Facebook button code-->
<!--<div id="fb-root"></div>-->
<!--<script>(function(d, s, id) {-->
<!--        var js, fjs = d.getElementsByTagName(s)[0];-->
<!--        if (d.getElementById(id)) return;-->
<!--        js = d.createElement(s); js.id = id;-->
<!--        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";-->
<!--        fjs.parentNode.insertBefore(js, fjs);-->
<!--    }(document, 'script', 'facebook-jssdk'));</script>-->

<!-- ******HEADER****** -->
<header id="header" class="header">
    <div class="container">
        <h1 class="logo float-left">
            <a class="scrollto" href="#promo">
                <span class="logo-title">Dinopy</span>
            </a>
        </h1><!--//logo-->
        <nav id="main-nav" class="main-nav navbar-expand-md float-right" role="navigation">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button><!--//nav-toggle-->

            <div class="navbar-collapse collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item sr-only"><a class="nav-link scrollto" href="#promo">Home</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#features">Features</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#docs">Projects</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#license">Support us</a></li>
                    <li class="nav-item last"><a class="nav-link scrollto" href="#contact">Contact</a></li>
                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->
    </div>
</header><!--//header-->

<!-- ******PROMO****** -->
<section id="promo" class="promo section offset-header">
    <div class="container text-center">
        <h2 class="title">Dino<span class="highlight">py</span></h2>
        <p class="intro">We are coding our world!</p>
        <!--        <div class="btns">-->
        <!--        <a class="btn btn-cta-secondary" href="https://themes.3rdwavemedia.com/" target="_blank">Demo</a>-->
        <!--        <a class="btn btn-cta-primary" href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/devaid-free-bootstrap-theme-for-developers-side-projects/" target="_blank">Download</a>-->
        <!--        </div>-->
        <!--        <ul class="meta list-inline">-->
        <!--        <li class="list-inline-item"><a href="https://github.com/xriley/devAid-Theme" target="_blank">View on GitHub</a></li>-->
        <!--        <li class="list-inline-item"><a href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/devaid-free-bootstrap-theme-for-developers-side-projects/" target="_blank">Full Documentation</a></li>-->
        <!--        <li class="list-inline-item">Created by: <a href="https://themes.3rdwavemedia.com/" target="_blank">Xiaoying Riley</a> at 3rd Wave Media</li>-->
        <!--        </ul>&lt;!&ndash;//meta&ndash;&gt;-->
    </div><!--//container-->
    <div class="social-media">
        <div class="social-media-inner container text-center">
            <!--            <br><br>-->
            <!--            <ul class="list-inline mb-2">-->
            <!--            <li class="list-inline-item facebook-like">-->
            <!--            <div class="fb-like" data-href="https://themes.3rdwavemedia.com/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div></li><!–//facebook-like–>-->
            <!--            <!–// Generate github buttons: https://github.com/mdo/github-buttons –>-->
            <!--            <li class="list-inline-item github-star"><a class="github-button" href="https://github.com/xriley/devaid-theme" data-icon="octicon-star" aria-label="Star xriley/devaid-theme on GitHub">Star</a></li>-->
            <!--            </ul>-->
        </div>
    </div>
</section><!--//promo-->

<!-- ******ABOUT****** -->
<section id="about" class="about section">
    <div class="container">
        <h2 class="title text-center">What is Dinopy?</h2>
        <p class="intro text-center">Dinopy is a little team which lose their nights developing various
            software products. Work on our team is like that:</p>
        <div class="row">
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="fas fa-heart"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Work with love</h3>
                    <p>We invest love in our projects, so we become more efficient, creativity is unlimited, good ideas
                        grow as we work.</p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="far fa-clock"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Time saver</h3>
                    <p>We work as much as possible to bring applications, as quickly as possible into a usable state,
                        because we are also excited to use them.</p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="fas fa-crosshairs"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Target</h3>
                    <p>We want to find innovative ideas in developed applications, but not to forget the nostalgia of
                        past times.</p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="clearfix visible-md"></div>
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="fas fa-mobile-alt"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Mobile-friendly</h3>
                    <p>We want to develop mainly phone applications because it is much more helpful in any
                        situation.</p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="fas fa-code"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Easy to customise</h3>
                    <p>We want to make applications as user-friendly as possible to provide the freedom to customize how
                        to work.</p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="item col-lg-4 col-md-6 col-12">
                <div class="icon-holder">
                    <i class="fas fa-coffee"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Little game break</h3>
                    <p>Sometimes we also need a break, so we stop developing and we start to relax playing different
                        games.</p>
                </div><!--//content-->
            </div><!--//item-->
        </div><!--//row-->
    </div><!--//container-->
</section><!--//about-->

<!-- ******FEATURES****** -->
<section id="features" class="features section">
    <div class="container text-center">
        <h2 class="title">Features</h2>
        <ul class="feature-list list-unstyled">
            <li><i class="fas fa-check"></i> C/C++/C#</li>
            <li><i class="fas fa-check"></i> PHP</li>
            <li><i class="fas fa-check"></i> MySql</li>
            <li><i class="fas fa-check"></i> A lot of passion</li>
            <li><i class="fas fa-check"></i> A lot of patience</li>
            <li><i class="fas fa-check"></i> Fully responsive</li>
        </ul>
    </div><!--//container-->
</section><!--//features-->

<!-- ******DOCS****** -->
<section id="docs" class="docs section">
    <div class="container">
        <div class="docs-inner">
            <h2 class="title text-center">Get Started</h2> <hr>
            <div class="block">
                <h3 class="sub-title text-center">OneDeck</h3>
                <h6 class="sub-title text-center">Many games with a single deck</h6>
                <p style="text-indent: 40px">OneDeck is a mobile app, more specifically a collection of traditional Romanian card games
                    <br>(Macaua, Razboi, etc.). The application is made in Unity (a game development program)
                    and programmed in C# using a PHP server to
                    connect more people to each other and to checks all the moves of the players to
                    avoid being cheaters, because it&#39;s not a simple card game it&#39;s a multiplayer
                    game. To keep all game statuses and to synchronize them with players, I use a
                    MySQL database where are all the details of the current games such as what the
                    card is on the table, who is next or what cards are left in the deck.</p>
                <ul class="list-unstyled">
                    <li><strong>Platform:</strong> PC, Andorid</li>
                    <li><strong>Application type:</strong> Card game</li>
                    <li><strong>Languages:</strong> Romanian, English</li>
                </ul>
                <div class="text-center">
                    <img id="img1" class="img-fluid img-logo" src="/assets/images/OneDeckLogo.png" alt=""/>
                    <br>
                    <a href='https://play.google.com/store/apps/details?id=com.TechNx.OneDeck&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1/'
                       target="_blank"><img class="img-fluid img-button" alt='Get it on Google Play'
                                            src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png'/></a>
                    <a class="btn btn-cta-primary" href="" target="_blank">Download for PC</a>
                </div><!--//code-block-->
            </div><!--//block-->
        </div><!--//docs-inner-->
    </div><!--//container-->
</section><!--//features-->

<!-- ******LICENSE****** -->
<section id="license" class="license section">
    <div class="container">
        <div class="license-inner">
            <h2 class="title text-center">Support us</h2>
            <!--<div class="info">-->
            <!--<p>This Bootstrap theme is made by UX/UI designer <a href="https://twitter.com/3rdwave_themes" target="_blank">Xiaoying Riley</a> at 3rd Wave Media for developers and is <strong>100% FREE</strong> under the <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons Attribution 3.0 License (CC BY 3.0)</a></p>-->
            <!--<p><strong>[Tip for developers]:</strong> If your project is open source, you might want to put a <a href="https://www.paypal.com/us/cgi-bin/?cmd=_donate-intro-outside" target="_blank">PayPal "Donate" button</a> below so your users can express their gratitude. If your project is commercial, you can put a <a href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_singleitem-intro-outside" target="_blank">PayPal "Buy Now" button</a> instead.</p>-->
            <!--</div>&lt;!&ndash;//info&ndash;&gt;-->
            <div class="cta-container">
                <div class="speech-bubble">
                    <p class="intro">If you want to give us your support, we will be grateful to you, this motivates us
                        to continue working hard.</p>
                    <div class="icon-holder  text-center"><i class="far fa-smile"></i></div>
                </div><!--//speech-bubble-->
                <div class="btn-container  text-center">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="Y245UFZEFPH2A">
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0"
                               name="submit" alt="PayPal - The safer, easier way to pay online!">
                        <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                    </form>
                </div><!--//btn-container-->
            </div><!--//cta-container-->
        </div><!--//license-inner-->
    </div><!--//container-->
</section><!--//how-->

<!-- ******CONTACT****** -->
<section id="contact" class="contact section has-pattern">
    <div class="container">
        <div class="contact-inner">
            <h2 class="title  text-center">Contact</h2>
            <p class="intro  text-center">We hope you like our work.<br>Feel free to get in touch if you have any
                questions or suggestions.</p>
            <div class="author-message">
                <div class="profile">
                    <img class="img-fluid" src="/assets/images/profile.png" alt=""/>
                </div><!--//profile-->
                <div class="speech-bubble">
                    <h3 class="sub-title">We are always looking for feedback!</h3>
                    <p>We are always glad to receive opinions from our users, because we can make really useful
                        improvements based on their experiences.</p>
                    <p>So we await feedback, especially the problems encountered at our email address: <strong>dinopyco@dinopy.com</strong>
                    </p>
                    <div class="source">
                        <span class="name">Neculache Nicu</a></span>
                        <!--<a href="https://twitter.com/3rdwave_themes" target="_blank">-->
                        <br>
                        <span class="title">CEO/Product Manager/Programmer</span>
                    </div><!--//source-->
                </div><!--//speech-bubble-->
            </div><!--//author-message-->
            <div class="clearfix"></div>
            <div class="info text-center">
                <h4 class="sub-title">Get Connected</h4>
                <ul class="social-icons list-inline">
                    <!--<li class="list-inline-item"><a href="https://twitter.com/3rdwave_themes" target="_blank"><i class="fab fa-twitter"></i></a></li>-->
                    <li class="list-inline-item"><a href="https://www.facebook.com/" target="_blank"><i
                                    class="fab fa-facebook-f"></i></a></li>

                    <!--<li class="list-inline-item"><a href="https://medium.com/@3rdwave_themes/" target="_blank"><i class="fab fa-medium-m"></i></a></li>  -->
                    <!--<li class="list-inline-item"><a href="https://dribbble.com/Xiaoying" target="_blank"><i class="fab fa-dribbble"></i></a></li>   -->
                    <li class="list-inline-item last"><a href="mailto:dinopyco@dinopy.com" target="_blank"><i
                                    class="fas fa-envelope"></i></a></li>
                </ul>
            </div><!--//info-->
        </div><!--//contact-inner-->
    </div><!--//container-->
</section><!--//contact-->

<!-- ******FOOTER****** -->
<footer class="footer">
    <div class="container text-center">
        <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
        <small class="copyright">Designed with <i class="fas fa-heart"></i> by <a href="https://themes.3rdwavemedia.com"
                                                                                  target="_blank">Xiaoying Riley</a> for
            developers</small>
    </div><!--//container-->
</footer><!--//footer-->

<!-- Javascript -->
<script type="text/javascript" src="/assets/plugins/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jquery-scrollTo/jquery.scrollTo.min.js"></script>
<script type="text/javascript" src="/assets/plugins/prism/prism.js"></script>
<script type="text/javascript" src="/assets/js/main.js"></script>


</body>
</html> 

