<!DOCTYPE html>
<html lang="en">

<head>
    <title>TechNx | Privacy</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Privacy policy <?= $this->data['game'] ?>">
    <meta name="author" content="Neculache Nicu">

    <?php require_once VIEW . 'import.phtml' ?>
</head>

<body>
<!-- ******HEADER****** -->
<header id="header" class="header">
    <div class="container">
        <h1 class="logo float-left">
            <a href="/home">
                <span class="logo-title">TechNx</span>
            </a>
        </h1><!--//logo-->
        <nav id="main-nav" class="main-nav navbar-expand-md float-right" role="navigation">
            <div class="navbar-fixed-top" id="navbar">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="/home">Home</a></li>
                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->
    </div>
</header><!--//header-->

<section class="blue-line"></section>

<!-- ******DOCS****** -->
<section id="docs" class="docs section">
    <div class="container">
        <div class="docs-inner">

            <?php
            if (!file_exists(VIEW . 'privacy_policy' . DIRECTORY_SEPARATOR . $this->data['game'] . '.html'))
                Application::redirectTo();
            else include_once VIEW . 'privacy_policy' . DIRECTORY_SEPARATOR . $this->data['game'] . '.html'
            ?>

        </div><!--//docs-inner-->
    </div><!--//container-->
</section><!--//features-->

<!-- ******FOOTER****** -->
<footer class="footer">
    <div class="container text-center">
        <small class="copyright">Designed with <i class="fas fa-heart"></i></small>
    </div><!--//container-->
</footer><!--//footer-->

</body>
</html>