<!DOCTYPE html>
<html lang="en">

<head>
    <title>TechNx | Privacy</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Privacy policy <?= $this->data['game'] ?>">
    <meta name="author" content="Neculache Nicu">

    <!-- ../favicon -->
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="../favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="apple-touch-icon" sizes="57x57" href="../favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="../favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="../favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="../favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="../favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="../favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../favicon/favicon-16x16.png">
    <link rel="manifest" href="../favicon/manifest.json">

    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- FontAwesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"
            integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9"
            crossorigin="anonymous"></script>
    <!-- Global CSS -->
    <link rel="stylesheet" href="../assets/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="../assets/plugins/prism/prism.css">
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="../assets/theme.css">
    <!-- GitHub Button -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</head>

<body>
<!-- ******HEADER****** -->
<header id="header" class="header">
    <div class="container">
        <h1 class="logo float-left">
            <a href="/home">
                <span class="logo-title">TechNx</span>
            </a>
        </h1><!--//logo-->
    </div>
</header><!--//header-->

<section class="blue-line"></section>

<!-- ******DOCS****** -->
<section id="docs" class="docs section">
    <div class="container">
        <div class="docs-inner">

<?php
//            if(!file_exists(VIEW . 'privacy_policy' . DIRECTORY_SEPARATOR . $this->data['game'] . '.html'))
//                Application::redirectTo();
//            else include_once VIEW . 'privacy_policy' . DIRECTORY_SEPARATOR . $this->data['game'] . '.html'
//            ?>

        </div><!--//docs-inner-->
    </div><!--//container-->
</section><!--//features-->

<!-- ******FOOTER****** -->
<footer class="footer">
    <div class="container text-center">
       <small class="copyright">Designed with <i class="fas fa-heart"></i></small>
    </div><!--//container-->
</footer><!--//footer-->

</body>
</html>